// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqvum5plwm3BndV3ze-xD2qpD0jq0OtlQ',
    appId: '1:1066300392478:web:f06c61f83263d1d7ab9a0f',
    messagingSenderId: '1066300392478',
    projectId: 'admission-hero',
    authDomain: 'admission-hero.firebaseapp.com',
    storageBucket: 'admission-hero.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqvum5plwm3BndV3ze-xD2qpD0jq0OtlQ',
    appId: '1:1066300392478:android:f06c61f83263d1d7ab9a0f',
    messagingSenderId: '1066300392478',
    projectId: 'admission-hero',
    authDomain: 'admission-hero.firebaseapp.com',
    storageBucket: 'admission-hero.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqvum5plwm3BndV3ze-xD2qpD0jq0OtlQ',
    appId: '1:1066300392478:ios:f06c61f83263d1d7ab9a0f',
    messagingSenderId: '1066300392478',
    projectId: 'admission-hero',
    authDomain: 'admission-hero.firebaseapp.com',
    storageBucket: 'admission-hero.firebasestorage.app',
    iosBundleId: 'com.admissionhero.app',
  );
}
